### ISSUE TITLE
task: exit on error

### ISSUE THREAD

**Issue by utkarshgupta137** [aaronriekenberg/rust-parallel#13]
Currently, rust-parallel doesn't exit (or even warn about) when a task exits unsuccessfully. I've changed this behavior in my fork: https://github.com/utkarshgupta137/rust-parallel/commit/a39253d1f3ea7eb225dfeded7dd432f53e3823f6.
I guess to add it to this crate, we'll probably want to add another option such as `--keep-going`. But it should still exit with an error status.
What do you think?

**Comment by aaronriekenberg** [comment]
Agree to add more logging when a child process fails (currently there is only 1 debug log of exit status not enabled by default https://github.com/aaronriekenberg/rust-parallel/blob/main/src/command.rs#L64), 

Also I like the idea to have option to exit rust-parallel with non-0 status when any child process fails.  For backwards compatibility will probably add a new option like `--exit-on-error` that keeps current behavior by default.

Thanks for reporting and the link to your fork @utkarshgupta137 

Will work on above.

**Comment by utkarshgupta137** [comment]
I feel like this is more of a bug. Almost all the tools have a --keep-going option rather than an --exit-on-error function. I left some jobs running one night & I was very surprised when the jobs continued after the initial failure.

**Comment by aaronriekenberg** [comment]
Both GNU parallel and xargs will keep going even if a command exits unsuccessfully.  Both return non-zero exit status when a job fails.  rust-parallel also keeps going but always returns 0 exit status.

For GNU parallel the default for `--halt-on-error` is `never` https://www.gnu.org/software/parallel/parallel.html#exit-status. This can be changed to `now,fail=1` to fail immediately on first job failure.

@utkarshgupta137 Could you provide an example command line for how you are running your job so that it exits on first error with other tools?

```
$ head -3 /usr/share/dict/words  | parallel cat
cat: A: No such file or directory
cat: AA: No such file or directory
cat: AAA: No such file or directory
$ echo $?
3
```

```
$ head -3 /usr/share/dict/words  | parallel --halt now,fail=1 cat
cat: A: No such file or directory
parallel: This job failed:
cat A
$ echo $?
1
```

```
$ head -3 /usr/share/dict/words  | xargs -P4 -L1 cat
cat: A: No such file or directory
cat: AA: No such file or directory
cat: AAA: No such file or directory
$ echo $?
123
```

```
$ head -3 /usr/share/dict/words  | rust-parallel cat
/usr/bin/cat: AA: No such file or directory
/usr/bin/cat: AAA: No such file or directory
/usr/bin/cat: A: No such file or directory
$ echo $?
0
```

**Comment by utkarshgupta137** [comment]
I guess you're right. I was comparing rust-parallel to tools like cargo which always have halt on error, but it probably makes more sense to compare it to parallel or xargs in this case.
I would definitely appreciate correct exit codes (something which my commit doesn't support).

**Comment by utkarshgupta137** [comment]
I've created a patch: https://github.com/utkarshgupta137/rust-parallel/commit/cdf1ca860613c17de4c1c8dea0dc76752c651f88. Happy to raise a PR if you don't have a different approach in mind.

**Comment by aaronriekenberg** [comment]
Yes @utkarshgupta137 I would be happy to review a PR with this patch.

Thanks!

**Comment by aaronriekenberg** [comment]
Fixed in https://github.com/aaronriekenberg/rust-parallel/pull/14

**Comment by aaronriekenberg** [comment]
Sure - I still like the idea above to add CLI argument `--exit-on-error` option to exit when the first command failure happens.

This option would be disabled by default for backwards compatibility, also this is similar to default behavior in xargs and GNU Parallel.

**Comment by aaronriekenberg** [comment]
Updates in version 1.15.0

* Improve error handling and add to manual https://github.com/aaronriekenberg/rust-parallel/wiki/Manual#error-handling
  * Log errors for commands and at end of main log number of failing commands.
  * If at least one command fails rust-parallel exits with status 1
* Add option `--exit-on-error` to specify rust-parallel exits with status 1 immediately when first command failure is seen.

**Comment by utkarshgupta137** [comment]
Thanks will test & re-open in case of issues!
