### ISSUE TITLE
Cartisian product supporting named arguments

### ISSUE THREAD

**Issue by rtbs-dev** [aaronriekenberg/rust-parallel#16]
So far working nicely for my benchmark dataset generation task. I need to sweep over some keyword/named arguments (`--kwarg X`), and I see GNU parallel can potentially do this via [--header](https://unix.stackexchange.com/questions/711517/gnu-parallel-with-named-arguments)? 

E.g. see this from my custom command `random-graph-walks kind size --n-walks --n-jumps --seed`, where the named arguments have default values, and I want to have `rust-parallel` sweep over `--seed`s without giving it n-walks and n-jumps input (they would stay randomized). 

 ```bash
rust-parallel -p random-graph-walks ::: tree block ::: 5 10 15
```

that works just fine to loop over combinations of (kind,size). But if I want to provide `--seed ` options, how would I specify? This doesn't work: 

 ```bash
rust-parallel -p random-graph-walks ::: tree block ::: 5 10 15 ::: --seed 2 5 10
```

complaining that parameter 'seed' requires an argument ( meaning, --seed, 2,5,10 all get passed as `n-walks` individually)

**Comment by aaronriekenberg** [comment]
One way to do this currently would be using regular expression groups to rewrite the commands - I think something like this should work (here using `echo` for demo):

```
rust-parallel --dry-run -r '(.*) (.*) (.*)' echo {1} {2} --seed {3} ::: tree block ::: 5 10 15 ::: 2 5 10
```

regex pattern matches each argument group and `{1}` `{2}` `{3}` are numbered capture groups - you can write arbitrary commands similar to above using these.


In your case I think this command should work:

**Comment by aaronriekenberg** [comment]
Looks like GNU parallel can use --header option in this way for your example:

```
parallel --header : random-graph-walks {kind} {size} --seed {seed}  ::: kind tree block ::: size 5 10 15 ::: seed 2 5 10
```

From [this reference](https://www.gnu.org/software/parallel/parallel_examples.html#example-for-loops-with-column-names), `--header :` lets the first argument after each `:::` be a named alias that gets replaced - in this example names are kind, size, seed.

So far rust-parallel does not support --header option but can consider adding this.  The options in previous comment using regex/bash function could be workarounds for now.

@rtbs-dev am I understanding your use case correctly?  Thanks!

**Comment by rtbs-dev** [comment]
Awesome, yes! This is a super helpful pattern for parameter sweeps. I've been successfully using the regex version you posted and it definitely works nicely, though something like the header option might be very nice to simplify things.

 Not sure if you're wanting feature parity, since imo the header syntax is a little weird for gnu-parallel. Open to any syntactic sugar, really, that implements argument interpolation for combinations of variables.

**Comment by aaronriekenberg** [comment]
Working in this branch https://github.com/aaronriekenberg/rust-parallel/tree/autoregex

With these changes below commands work and are equivalent:

```
rust-parallel --auto-interpolate-args echo {1} {2} --seed {3} ::: tree block ::: 5 10 15 ::: 2 5 10

rust-parallel --auto-interpolate-named-args echo {kind} {size} --seed {seed} ::: kind tree block ::: size 5 10 15 ::: seed 2 5 10
```

Todo:
1. tests
2. code cleanup
3. Consider better option names - currently using auto-interpolate-args and auto-interpolate-named-args.  I agree `--header :` in GNU parallel is not very obvious :)

**Comment by aaronriekenberg** [comment]
In version [1.18.0](https://github.com/aaronriekenberg/rust-parallel/releases/tag/v1.18.0) - added support for [automatic numbered variable interpolation](https://github.com/aaronriekenberg/rust-parallel/wiki/Manual#commands-from-arguments)

In addition to above options - the following will work now:

```
rust-parallel --dry-run echo {1} {2} --seed {3} ::: tree block ::: 5 10 15 ::: 2 5 10
```

May in future consider adding support for named arguments similar to `--header :` in GNU parallel, but starting with above only for now :)

Thanks @rtbs-dev !
